//v98 (c) 2008-2014 33Across Inc. All Rights Reserved

Tynt=window.Tynt||[];
if(typeof Tynt.TIL=="undefined"){(function(){var Lb=function(){function K(a){var b=K.options;a=b.parser[b.strictMode?"strict":"loose"].exec(a);for(var c={},d=14;d--;)c[b.key[d]]=a[d]||"";c[b.q.name]={};c[b.key[12]].replace(b.q.parser,function(e,f,g){if(f)c[b.q.name][f]=g});return c}K.options={strictMode:false,key:["source","protocol","authority","userInfo","user","password","host","port","relative","path","directory","file","query","anchor"],q:{name:"queryKey",parser:/(?:^|&)([^&=]*)=?([^&]*)/g},parser:{strict:/^(?:([^:\/?#]+):)?(?:\/\/((?:(([^:@]*)(?::([^:@]*))?)?@)?([^:\/?#]*)(?::(\d*))?))?((((?:[^?#\/]*\/)*)([^?#]*))(?:\?([^#]*))?(?:#(.*))?)/,
loose:/^(?:(?![^:@]+:[^:@\/]*@)([^:\/?#.]+):)?(?:\/\/)?((?:(([^:@]*)(?::([^:@]*))?)?@)?([^:\/?#]*)(?::(\d*))?)(((\/(?:[^?#](?![^?#\/]*\.[^?#\/.]+(?:[?#]|$)))*\/?)?([^?#\/]*))(?:\?([^#]*))?(?:#(.*))?)/}};var h=document,l=h.body,s=h.documentElement,V=eval("/*@cc_on!@*/false"),za=function(a,b){for(var c="",d=0;d<b;d++)c+=a;return c},B=za("a",50),C=(Tynt.e||"")+"ic.tynt.com",Ya=(Tynt.e||"")+"de.tynt.com/deb/",Za=(Tynt.e||"")+"cdn.tynt.com",W=C+"/b/s",Aa=(Tynt.e||"")+"id.tynt.com",u=function(){return(new Date).getTime()},
z=function(a){return a.replace(/^\s+|\s+$/g,"")},G=function(a,b){for(var c in a)if(a.hasOwnProperty(c))b[c]=a[c]},q=function(a,b,c){a=h.createElement(a);G(b,a);G(c,a.style);return a},P=function(){for(var a=Tynt,b={},c=a.length,d=[],e=0;e<c;e++)if(!b[a[e]]){b[a[e]]=true;d.push(a[e])}return d.join("~")},D,Q;if(window.addEventListener){D=function(a,b,c){a.addEventListener(b,c,false)};Q=function(a,b,c){a.removeEventListener(b,c,false)}}else{D=function(a,b,c){a.attachEvent("on"+b,c)};Q=function(a,b,c){a.detachEvent("on"+
b,c)}}var R=function(a,b){var c=location.hostname.split("."),d,e=2;do{d=c.slice(c.length-e,c.length).join(".");d=a+";path=/;domain=."+d+";"+b;h.cookie=d;e++}while(h.cookie.indexOf(a)==-1&&e<=c.length);if(h.cookie.indexOf(a)==-1){d=a+";path=/;"+b;h.cookie=d}},X=function(a){h.readyState=="complete"?a():D(window,"load",function(){setTimeout(function(){if(typeof h.readyState=="undefined"&&!V)h.readyState="complete";a()},10)})},r=function(a,b){var c=[],d=function(e,f){var g="http://"+e.replace("id="+B,
"id="+P());if(g.indexOf(C+"/b/p?")>-1&&typeof Tynt.b=="string")g+="&b="+Tynt.b;var j=new Image(1,1);if(f)j.onerror=f;j.src=g};r=function(e,f){c.push([e,f])};X(function(){r=d;for(var e=0;e<c.length;e++)r(c[e][0],c[e][1]);c=null});r(a,b)},la=function(a){a=q("script",{async:"async",src:"http://"+a});var b=document.getElementsByTagName("script")[0];b.parentNode.insertBefore(a,b)},Ba=function(a){var b=[],c="",d;for(d in a)if(a.hasOwnProperty(d)){b.push(c,d,"=",a[d]);c="&"}return b.join("")},L=function(a){for(var b=
0,c=a.length<100?a.length:100,d=0;d<c;d++)b+=a.charCodeAt(d);a=Math.floor(Math.random()*3844);c=Math.abs(u()-12281184E5);return Ca(c,7)+Ca((b+a)%3844,2)},Da=function(a){if(a<62)return"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(this);else{var b=Math.floor(a/62);a=a-b*62;return b>=62?Da(b)+"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(a):"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(b)+"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(a)}},
Ca=function(a,b){var c=Da(a);return za("0",b-c.length)+c},Y=function(a){return(a=z(a))?a.split(/\s+/i).length:0},S=z((h.title||location.hostname).toString()).replace(RegExp(location.hash,"g"),""),Ea=function(){for(var a=h.getElementsByTagName("link"),b=0;b<a.length;b++)if(a[b].getAttribute("rel")&&a[b].getAttribute("rel").match("canonical")&&a[b].getAttribute("href")){a=a[b].getAttribute("href");b=location.protocol+"//"+location.host+location.pathname;var c=h.getElementsByTagName("base")[0];if(c)if(c=
c.getAttribute("href"))b=c;if(!a.match(/^http/)){if(a.charAt(0)=="/"){c=b.indexOf("/",9);if(c>-1)b=b.slice(0,c)}else{c=b.lastIndexOf("/");if(c>9)b=b.slice(0,c+1);else b+="/"}a=b+a}return a}return""},E=function(a){return a.replace(/^https?:\/\//,"")},ma=function(a,b){for(var c=b+"=",d=a.split(";"),e=0;e<d.length;e++){for(var f=d[e];f.charAt(0)==" ";)f=f.substring(1,f.length);if(f.indexOf(c)===0)return f.substring(c.length,f.length)}return null},$a=function(){var a=ma(h.cookie,"tracertraffic"),b=encodeURIComponent(E(Ea())),
c=h.location.hash;c=/tynt=/.test(c)?c.match(/tynt=?([^?&$#]*)/)[1]:false;var d=C+"/b/p?id="+B+(a?"&et="+a:"")+(c?"&a="+c:"")+"&ts="+u(),e=d+(b?"&cu="+b:""),f=e+(h.referrer?"&r="+encodeURIComponent(E(h.referrer)):"");a=f+"&t="+encodeURIComponent(S);r(a,function(){r(f,function(){r(e,function(){r(d)})})})},ab=function(){X(function(){var a=[Ya,"v2?id=",P(),"&r=",encodeURIComponent(E(h.referrer))].join("");la(a)})},Fa=function(a){var b=a.trace_type;delete a.trace_type;var c=a.g;delete a.g;for(var d=[],
e=["id","wc","f","w","h","t","c"],f=0;f<e.length;f++){var g=e[f],j=a[g];j&&d.push([g,encodeURIComponent(j).replace(/\'/g,"%27")]);delete a[g]}for(var k in a)if(a.hasOwnProperty(k))(e=a[k])&&d.push([k,encodeURIComponent(e).replace(/\'/g,"%27")]);a=[];f=2048-(("http://"+C+"/a/t/x#?").length+(3+c.length)+5);g=d.length;var p=j=0,o=0,v,m,H,t,w=0;for(a[w]={g:c,tp:null};j<g&&a.length<35;){v=d[j][0];k=d[j][1];H=v.length+2;m=f-H-p;if(m>0){e=k.substring(o,o+m);t=e.slice(-2).indexOf("%");if(t>-1){e=k.substring(o,
o+m-2+t);p+=t+2}p+=e.length+H;o+=e.length;a[w][v]=e}else p=f;if(p>=f){a[++w]={g:c,p:w};p=0}if(o>=k.length){j++;o=0}}a[0].tp=a.length;r(C+"/b/t/"+b+"?"+Ba(a[0]));for(c=1;c<a.length;c++)r(C+"/b/x/"+b+"?"+Ba(a[c]))},na=function(){var a=[];return function(b){for(var c=a.length-1;c>=0;c--)if(a[c]==b)return false;a.unshift(b);a.length>3&&a.pop();return true}},bb=na(),cb=na(),db=function(){var a,b=function(){window.removeEventListener("blur",b,false);oa(a);return true};return function(c){a=c.target||c.srcElement;
window.removeEventListener("blur",b,false);if(a.nodeName=="IMG"&&a.parentNode.nodeName!="A"){window.addEventListener("blur",b,false);setTimeout(function(){h.removeEventListener("blur",b,false)},1E4)}return true}}(),Ga=function(a){oa(a.target||a.srcElement,true)},Z,Ha=function(a){a=a.target||a.srcElement;Z=a.nodeName=="IMG"?a:null},pa=function(){var a=function(g){return typeof g.pageX=="number"?{x:g.pageX-(s.scrollLeft?s.scrollLeft:l.scrollLeft),y:g.pageY-(s.scrollTop?s.scrollTop:l.scrollTop)}:{x:g.clientX,
y:g.clientY}},b=function(g){g=a(g);return g.x<=0||g.y<=0||g.x>=l.clientWidth||g.y>=l.clientHeight},c=function(g){g=a(g);return g.x<=0||g.y<=0||g.x>=s.clientWidth||g.y>=s.clientHeight},d=function(g){return g.target.nodeName=="#document"},e=function(g){g=a(g);return g.x<=4||g.y<=4||g.x>=s.clientWidth-4||g.y>=s.clientHeight-4},f=function(g){f=navigator.userAgent.match("MSIE")?!h.compatMode||h.compatMode.indexOf("CSS")==-1?b:c:navigator.userAgent.match("Firefox")?d:e;f(g)};return function(g){if(Z&&f(g)){oa(Z);
Z=null}return true}}(),Ia=function(){return/tracer=test|tracer=no_tracing|disableTracer=/.test(location.href)||/disableTracer=y/.test(h.cookie)};Tynt.ci=function(){var a;return function(b,c){a=c||a;var d=W+["?ci=",b,"&id=",B,"&g=",a,"&r=",encodeURIComponent(E(h.referrer)),"&ts=",u()].join("");r(d)}}();Tynt.st=function(){var a;return function(b,c,d){a=d||a;b=W+["?",encodeURIComponent(b),"=",encodeURIComponent(c),"&id=",B,"&g=",a,"&r=",encodeURIComponent(E(h.referrer)),"&href=",encodeURIComponent(E(h.location.href)),
"&ts=",u()].join("");r(b)}}();var qa;if(Tynt.c)qa=function(){};else{Tynt.c=true;Tynt.m=Tynt.m||[];Tynt.n=Tynt.n||[];qa=function(){var a=true,b,c=function(d,e){var f={id:B,wc:Y(e),c:e,f:a?1:0,t:S};G(d,f);a=false;Fa(f)};if(window.addEventListener){navigator.userAgent.match(/Firefox\/2\b/)||l.addEventListener("copy",Ga,false);window.addEventListener("mousedown",Ha,false);window.addEventListener("dragleave",pa,false);window.addEventListener("dragexit",pa,false);h.addEventListener("contextmenu",db,false)}else{l.attachEvent("oncopy",
Ga);h.getElementsByTagName("html")[0].attachEvent("ondragleave",pa);l.attachEvent("onmousedown",Ha)}if(h.cookie.indexOf("tracertraffic=")!==-1)if(!h.referrer||h.referrer.indexOf(location.host)==-1)R("tracertraffic=0","expires=Thu, 01 Jan 1970 00:00:00 GMT");$a();ab();return function(d,e){if(!h.getElementById("tyntSh")){var f,g,j;if(e)if(!h.selection||!h.selection.createRange){g=getSelection();j=g.rangeCount>0&&g.getRangeAt(0);f=g.toString()}else{g=h.selection.createRange();j=g.duplicate();f=g.text}var k=
d.src;if(k&&!f&&cb(k)){g={trace_type:3,g:L(k),w:d.width,h:d.height};for(j=0;j<Tynt.n.length;j++)Tynt.n[j](g,k);c(g,k)}else if(f&&z(f).length&&d.nodeName!="TEXTAREA"&&d.nodeName!="INPUT"){k=bb(f);g={trace_type:1};if(k)b=L(f);g.g=b;for(var p=true,o=0;o<Tynt.m.length;o++)p=p&&Tynt.m[o](g,f,j,k);k&&p&&c(g,f)}}}}}if(typeof A==="undefined")var A={afterIpBlockCheck:[],afterDynamicConfig:[],afterCheckModules:[],afterProtectTynt:[],afterDynamicConfigAndDocumentLoaded:[]};var F=function(a,b){if(typeof A!==
"undefined"&&A.hasOwnProperty(a)&&A[a].hasOwnProperty("length"))for(var c=0;c<A[a].length;c+=1)typeof A[a][c]==="function"&&A[a][c](b)},$=function(a){a=a.charCodeAt(0);return 3584<=a&&a<=3711||11904<=a&&a<=12591||12688<=a&&a<=40959||63744<=a&&a<=64255||65072<=a&&a<=65103||131072<=a&&a<=173791||194560<=a&&a<=195103},Ja=function(a){a=a.getElementsByTagName("script");for(var b=a.length-1;b>=0;b--){var c=a[b];c.parentNode.removeChild(c)}},M=function(a,b){var c=Ea();c=c&&i.c!==false?c:location.href;c=
c.replace(/#(i|a)xzz=?(.*)$/g,"");c=c+"#"+("ixzz"+a);if(b)c+="&"+b;return c},eb=function(a,b){b=z(b);if(a.getElementsByClassName)return a.getElementsByClassName(b);if(a.querySelectorAll)return a.querySelectorAll("."+b);return function(){for(var c=a.getElementsByTagName("*"),d=[],e=0;e<c.length;e++)c[e].className.match(b)&&d.push(c[e]);return d}()},ra=function(a){return Object.prototype.toString.apply(a)==="[object Array]"},fb=function(a){if(typeof Array.prototype.toJSON!=="function")return JSON.stringify(a);
var b=Array.prototype.toJSON;delete Array.prototype.toJSON;a=JSON.stringify(a);Array.prototype.toJSON=b;return a},sa=h.defaultView,ta=V?!h.compatMode||h.compatMode.indexOf("CSS")==-1:false,gb=V?!("XMLHttpRequest"in window):false,aa=function(a){aa=typeof sa!="undefined"&&typeof sa.getComputedStyle!="undefined"?function(b){return sa.getComputedStyle(b,"")}:function(b){return b.currentStyle};return aa(a)},x={};x.t=3;x.p=6;x.w=7;x.f=8;x.i=9;x.l=10;x.g=11;x.ssbt=12;x.ssbf=13;x.ssbp=14;x.ssbl=15;x.ssbg=
16;var hb=function(a){a=a.match(/ixzz=?([^?$#]*)/);if(!a)return null;a=a[1].match(/&([^?$]*)/);if(Tynt.k)return Tynt.k.charAt(1);if(!a||!a[1])return null;return a[1]},Ka=function(a){var b=new Date(u()+864E5);R("tracertraffic="+a.toString(),"expires="+b.toUTCString())},ib=function(){if(Tynt.v)return false;Tynt.v=true;var a=location.href.match(/ixzz=?([^?&$#]*)/),b=(a&&a.length==2?a[1]:null)||Tynt.h;if(b&&!(h.referrer?K(h.referrer).host===K(h.location.hostname).host:false)){a=hb(location.href);b=C+
"/b/v"+["?g=",b,/\?trace_owner_view/.test(location.href)?"&o=y":"","&id=",B,a?"&s="+a:"","&r=",encodeURIComponent(E(h.referrer)),"&ts=",u()].join("");r(b);Ka(x[a]||1);return true}return false},I="http://"+(Tynt.e||"")+"cdn.tynt.com/images/ss/",La=typeof createImageMeme!=="undefined",jb=/Mobile|iP(hone|od|ad)|Android|BlackBerry|Tablet|IEMobile|Kindle|NetFront|Silk-Accelerated|(hpw|web)OS|Fennec|Minimo|Opera M(obi|ini)|Blazer|Dolfin|Dolphin|Skyfire|Zune/,J=J||"";J+=["#tyntSh div,#tyntSh span,#tyntSh img,#tyntSh a,div#tyntSh{margin:0;padding:0;border:0;font-size:100%;font:inherit;vertical-align:baseline;line-height:1;background:0;text-align:left}#tyntSh img,#tyntSh span{display:inline}#tyntSh div,div#tyntSh{display:block}div#tyntSh{z-index:9999999;position:absolute;height:62px;margin:10px;overflow:visible;background:#FFF;border-radius:5px;text-align:center;box-shadow: 0 2px 6px rgba(0,0,0,0.5)}div#tyntShTr{margin:-11px auto 0 auto;width:0;height:0;border-left:10px solid transparent;border-right:10px solid transparent;border-bottom:11px solid #F1F1F1}img#tyntShTw,img#tyntShP,img#tyntShFb,img#tyntShLi,img#tyntShGp{cursor:pointer;height:28px;width:28px;margin:3px 3px 2px 3px;vertical-align:bottom}div#tyntShPTL,div#tyntShHFL{color:#888;text-decoration:none;margin:0 0 2px 0;background-color:#F1F1F1;padding:2px 4px;border-radius:5px 5px 0 0}div#tyntShHFL{text-align:right;border-radius:0 0 5px 5px;margin:2px 0 0 0}div#tyntShHFL,span#tyntShHFLs,div#tyntShPTL{font:normal 8px Arial}",
"span#tyntShHFLs{cursor:pointer;"+(ta?"text-decoration:underline":"")+"}","span#tyntShHFLs:hover{color:#555;text-decoration:underline}div#tyntShCB{position:absolute;cursor:pointer;width:14px;height:14px;top:0;right:0;background-position:0 -14px;background-repeat:no-repeat}div#tyntShCB:hover{background-position: 0 0}"].join("");var y=function(){var a,b;return function(c,d,e){a=d||a;b=e||b;c=W+["?w=",c,"&id=",B,"&g=",a,"&wc=",b,"&r=",encodeURIComponent(E(h.referrer)),"&ts=",u()].join("");r(c)}}(),ba=
function(){return jb.test(navigator.userAgent||navigator.vendor||window.opera)},N=function(a){return(i.ss||"").indexOf(a)>-1},Ma=function(){return(i.ss||"").replace("p","").replace("m","").length},ca=function(a,b){return b.length>a?b.slice(0,a-1)+"\u2026":b},kb=function(a,b,c){if(typeof c==="undefined")c="w";b=M(b,c);return b=ca(114,a)+" "+b},n={words:0,_content:"",guid:null,isBar:function(a){a=a||"";return!!a.toString().match(/ssb/)},getContentFor:function(a){return n.isBar(a)?"":n._content},setContent:function(a){n._content=
a},getGuid:function(){return this.guid?this.guid:L(document.location.toString())},twitter:function(a,b,c){return q("img",{src:I+"t.png",title:"tweet this",id:a,onclick:function(){window.open("http://twitter.com/home?status="+encodeURIComponent(kb(n.getContentFor(c),n.getGuid(),c)),"tweet","width=723,height=251");y(b,n.getGuid(),n.words)}})},facebook:function(a,b,c){return q("img",{src:I+"fb.png",title:"share on Facebook",id:a,onclick:function(){var d=["http://www.facebook.com/dialog/feed?app_id=158472647611546&link=",
encodeURIComponent(M(n.getGuid(),c)),"&description=",encodeURIComponent(ca(140,n.getContentFor(c))),"&redirect_uri=",encodeURIComponent("http://cdn.tynt.com/close.html")].join("");window.open(d,"fbshare","width=985,height=450");y(b,n.getGuid(),n.words)}})},linkedin:function(a,b,c){return q("img",{src:I+"li.png",title:"share on LinkedIn",id:a,onclick:function(){var d;d=["http://www.linkedin.com/shareArticle?mini=true","&url=",encodeURIComponent(M(n.getGuid(),c)),"&title=",S];if(n.getContentFor(c)){d.push("&summary=");
d.push(encodeURIComponent(ca(255,n.getContentFor(c))))}d=d.join("");window.open(d,"lishare","width=520,height=450");y(b,n.getGuid(),n.words)}})},googleplus:function(a,b,c){return q("img",{src:I+"gp.png",title:"share on Google+",id:a,onclick:function(){var d=["https://plus.google.com/share?url=",encodeURIComponent(M(n.getGuid(),c))].join("");window.open(d,"gpshare","menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=600,width=600");y(b,n.getGuid(),n.words)}})},pinterest:function(){}},ua=function(a,
b,c){var d=a.createElement("style");d.id=b;d.type="text/css";b=a.createTextNode(c);d.styleSheet?d.styleSheet.cssText=b.nodeValue:d.appendChild(b);a.getElementsByTagName("head")[0].appendChild(d)},Na=function(a,b,c){var d,e=function(f,g,j){n.guid=g;n.setContent(f);n.words=Y(f);if(!(h.getElementById("tyntSh")||n.words<8)){y(0,n.guid,n.words);var k;if(!h.selection||!h.selection.createRange){f=q("span",{},{display:"inline"});g=j.startContainer;var p=j.endContainer,o=j.endOffset;try{var v=h.createRange();
v.setStart(p,o);v.setEnd(p,o);v.surroundContents(f);var m,H,t;o={top:0,left:0,bottom:0};var w=f&&f.ownerDocument;if(w){m=w.documentElement;if(typeof f.getBoundingClientRect!=="undefined")o=f.getBoundingClientRect();H="scrollTo"in w&&w.document?w:w.nodeType===9?w.defaultView||w.parentWindow:false;t={top:o.top,left:o.left,width:o.right-o.left,height:o.bottom-o.top};if(aa(f).position!="fixed"){t.top+=H.pageYOffset||m.scrollTop||0;t.left+=H.pageXOffset||m.scrollLeft||0}t.top+=m.clientTop||0;t.left+=m.clientLeft||
0;k=[t.left,t.top,t.width,t.height]}else k=null;k[2]=f.offsetHeight;f.parentNode.removeChild(f);v.detach();g.parentNode.normalize();p.parentNode.normalize()}catch(Mb){}typeof getSelection().setBaseAndExtent!="undefined"&&getSelection().setBaseAndExtent(j.startContainer,j.startOffset,j.endContainer,j.endOffset)}else{j=h.selection.createRange();v=ta?"offset":"bounding";k=[];k[0]=j[v+"Left"]+(s.scrollLeft||l.scrollLeft);k[1]=j[v+"Top"]+(s.scrollTop||l.scrollTop);k[2]=j.boundingHeight}k=k;d.style.left=
k[0]+"px";d.style.top=Math.max(k[1]+k[2],3)+"px";l.insertBefore(d,l.firstChild);D(l,"mousedown",O);D(l,"touchstart",O)}};(function(){h.getElementById("tyntShCSS")||ua(h,"tyntShCSS",J);d=q("div",{id:"tyntSh"},{width:Math.max(80,Ma()*34)+"px"});ta||d.appendChild(q("div",{id:"tyntShTr"}));var f=q("div",{id:"tyntShPTL",innerHTML:"Powered by Tynt"});d.appendChild(f);f=q("div",{id:"tyntShHFL"});f.appendChild(q("span",{id:"tyntShHFLs",innerHTML:"Don't show again",onclick:lb}));var g=q("div",{id:"tyntShCB",
title:"close",onclick:mb},{backgroundImage:"url("+(I+"x.png")+")"});N("f")&&d.appendChild(n.facebook("tyntShFb",4,"f"));N("t")&&d.appendChild(n.twitter("tyntShTw",3,"w"));N("l")&&d.appendChild(n.linkedin("tyntShLi",8,"l"));N("g")&&d.appendChild(n.googleplus("tyntShGp",9,"g"));if(La){var j=q("img",{src:I+"pi.png",title:"pin it",id:"tyntShP",onclick:function(){createImageMeme(void 0,void 0)}});La&&d.appendChild(j)}ba()||d.appendChild(f);d.appendChild(g)})();e(a,b,c);Na=e},mb=function(){O();y(2)},O=
function(a){var b=h.getElementById("tyntSh"),c=a?a.target||a.srcElement:{id:""};if(b&&!(c.id.indexOf("tyntSh")>-1)){Q(l,"mousedown",O);Q(l,"touchstart",O);l.removeChild(b);a&&y(1)}},lb=function(){O();var a=new Date(u()+31536E7);R("TyntSpeedShareHide=true","expires="+a.toUTCString());y(5)},da=function(){return!gb&&h.cookie.indexOf("TyntSpeedShareHide=true")==-1},nb=function(a,b,c){Ma()&&setTimeout(function(){da()&&Na(b,a.g,c)},1);return true};if(typeof i==="undefined")var i;A.afterDynamicConfigAndDocumentLoaded.push(function(a){if(a&&
a.ssb){ua(h,"tyntSbCSS",".tynt-speedshare-bar img{margin:0 3px;}");for(var b=eb(document,"tynt-speedshare-bar"),c,d=false,e=0;e<b.length;e++){c=b[e];if(a.ssb.indexOf("f")>-1){c.appendChild(n.facebook("tyntSbFb",16,"ssbf"));d=true}if(a.ssb.indexOf("t")>-1){c.appendChild(n.twitter("tyntSbTw",17,"ssbt"));d=true}if(a.ssb.indexOf("l")>-1){c.appendChild(n.linkedin("tyntSbLi",19,"ssbl"));d=true}if(a.ssb.indexOf("g")>-1){c.appendChild(n.googleplus("tyntSbGp",20,"ssbg"));d=true}}d?y(14):y(15)}});var ea=[],
T=[],Oa=[{x:970,y:250},{x:300,y:600},{x:300,y:1050},{x:970,y:90},{x:300,y:250},{x:970,y:250},{x:970,y:90},{x:180,y:150},{x:160,y:600},{x:728,y:90},{x:120,y:60},{x:88,y:31}],Pa=[/:\/\/[^\/]*?outbrain\.com/,/:\/\/ads\.yldmgrimg\.net/,/:\/\/[^\/]*?cdn\.adblade\.com/,/:\/\/[^\/]*?googlesyndication\.com/];J=J||"";J+=["div.tyntShIh,.tyntShIh div,.tyntShIh span{margin:0;padding:0;border:0;font-size:100%;font:inherit;vertical-align:baseline;line-height:1;background:0;text-align:left}.tyntShIh img,.tyntShIh span{display:inline}.tyntShIh div,div.tyntShIh{display:block;outline:0}",
"div.tyntShIh{position:absolute;cursor:default;background:transparent url("+(I+"pi.png")+") no-repeat;width:43px;height:21px;opacity:0;filter:alpha(opacity=0);z-index:9999999;-webkit-transition:opacity 0.5s;-moz-transition:opacity 0.5s}","div.tyntIhHover{opacity:1;filter:alpha(opacity=100);cursor:pointer}"].join("");var ob=function(a){a.getElementById("tyntShCSS")||ua(a,"tyntShCSS",J)},qb=function(a,b,c){var d=c.document,e=a.getBoundingClientRect(),f=(e.right+e.left+a.width)/2,g=(e.top+e.bottom+a.height)/
2,j;for(j=function(){var k={};for(k.x=f;k.x>e.left;k.x-=20)for(k.y=g;k.y>e.top;k.y-=20)if(d.elementFromPoint(k.x,k.y)===a)return k;k.x=-1;k.y=-1;return k}();j.y<=g&&d.elementFromPoint(j.x,j.y)===a;)j.y++;for(j.y--;j.x<=f&&d.elementFromPoint(j.x,j.y)===a;)j.x++;j.x--;j=pb(j,c);b.style.left=j.x-45+"px";b.style.top=j.y-22+"px"},pb=function(a,b){var c=b.document.documentElement;return{x:a.x+((b.pageXOffset||c.scrollLeft||0)+(c.clientLeft||0)),y:a.y+((b.pageYOffset||c.scrollTop||0)+(c.clientTop||0))}},
rb=function(a){if(i&&typeof i.sspe!=="undefined"){if(T.length===0)T=i.sspe.split(",");if(T.length!==ea.length)for(var b=0;b<T.length;b+=1)ea.push(RegExp(T[b]));for(b=0;b<ea.length;b+=1)if(a.getAttribute("src")&&ea[b].test(a.getAttribute("src")))return true}return false},sb=function(a){var b,c;for(b=0;b<Pa.length;b++)if(Pa[b].test(a.src))return true;for(b=0;b<Oa.length;b++){c=Oa[b];if(a.width===c.x&&a.height===c.y)return true}return false},tb=function(){if(!(Ia()||!da()||!N("p"))){var a=function(b){var c=
b.document,d=null,e,f=null,g,j,k,p;e=c.createElement("div");e.className="tyntShIh";c.body.appendChild(e);D(e,"click",function(){if(e.className=="tyntShIh tyntIhHover"&&da()){window.open("http://pinterest.com/pin/create/button/?url="+encodeURIComponent(M(L(f.src),"i"))+"&media="+f.src+"&description="+encodeURIComponent(ca(500,z(f.title||f.alt))));y(7)}});ob(c);D(c,"mouseover",function(m){if(!m)m=b.event;m=b.event?m.srcElement:m.target;if(m.nodeName==="IMG"&&m.height>=80&&m.width>=80&&m.src.indexOf("data:")!==
0&&!sb(m)&&!rb(m)&&m.getAttribute("nopin")!=="nopin"&&m.nopin!=="nopin")if(!(m===f&&e.showing)){f!==null&&f!==m&&o();f=m;f.__tyntPinItShow=true;d!==null&&clearTimeout(d);d=setTimeout(function(){if(f.__tyntPinItShow&&da()){qb(f,e,b);e.className="tyntShIh tyntIhHover";e.showing=true;f.__tyntPinItRecorded||y(6);f.__tyntPinItRecorded=true}},typeof i!=="undefined"&&typeof i.pt!=="undefined"&&i.pt=="i"?0:1E3);D(c,"mousemove",p)}});p=function(m){m=c.elementFromPoint(m.clientX,m.clientY);m!=f&&m!=e&&o()&&
Q(c,"mousemove",p)};var o=function(){if(e.showing){f.__tyntPinItShow=false;e.showing=false;e.className="tyntShIh";setTimeout(function(){e.style.left="-100px"},600);return true}return false};g=c.getElementsByTagName("iframe");for(k=g.length-1;k>=0;k--){j=g[k];try{!(j.src&&j.src.indexOf(location.protocol+"//"+location.hostname)!==0)&&j.getAttribute("nopin")!=="nopin"&&j.nopin!=="nopin"&&a(j.contentWindow)}catch(v){window.console&&console.log("Bad iframe access",v,j)}}};a(window)}},va=function(a){if(Tynt.sic)return false;
Tynt.sic=true;var b=document.createElement("script"),c=document.getElementsByTagName("script")[0];b.async="async";b.type="text/javascript";a=a;var d={"0":"sic-akamai.33across.com/javascripts/sic.js","1":"sic-akamai.33across.com/1/javascripts/sic.js"},e=Tynt.e||"";if(typeof a==="undefined"||!(a in d))a="0";b.src="http://"+e+d[a];c.parentNode.insertBefore(b,c);return true},fa=function(){var a=h.cookie.match(/tyntSICenable=(\d+?)/);return a?a[1]:false}();fa&&va(fa);var Qa={viglink:function(){Tynt.vglnk=
{api_url:"//vigapi.tynt.com/api",key:"f1f79f31e313bdb2b382c721aac77807",sub_id:""+ga};window.vglnk_self="Tynt.vglnk";(function(a,b){var c=a.createElement(b);c.type="text/javascript";c.async=true;c.src=("https:"==document.location.protocol?Tynt.vglnk.api_url:"//vig.tynt.com/api")+"/vglnk.js";var d=a.getElementsByTagName(b)[0];d.parentNode.insertBefore(c,d)})(document,"script")},track_selections:function(){var a=na();D(h,"mouseup",function(){var b="";if(!h.selection||!h.selection.createRange)b=getSelection().toString();
else{selection=h.selection.createRange();b=selection.text}b=z(b);if(b.length&&a(b)){b={id:B,g:L(b),wc:Y(b),c:b.slice(0,2E3),t:S,trace_type:2};Fa(b)}})},track_attribution_views:function(){trackAttributionView=true},sic:function(){va("0")},sic_v1:function(){va("1")}};A.afterDynamicConfig.push(function(){var a,b=i.p;if(b)for(a=0;a<b.length;a++)typeof Qa[b[a]]==="function"&&Qa[b[a]]();typeof F==="function"&&F("afterCheckModules")});var ub=Aa+"/ipb.js",wa=function(){return h.cookie.indexOf("ty_attributionBlockedByIp=t")!==
-1?true:false},Ra,vb=function(){Ra=setTimeout(function(){F("afterIpBlockCheck",i)},3E3);la(ub)};Tynt.ipb=function(a){clearTimeout(Ra);var b=false;if(ra(i.ipb)){for(var c=0;c<i.ipb.length;c++)if(a===i.ipb[c]){b=true;break}a=b;b=new Date;b.setHours(b.getHours()+1);b="expires="+b.toGMTString();R("ty_attributionBlockedByIp="+(a===true?"t":"f"),b)}F("afterIpBlockCheck",i)};var Sa=(Tynt.e||"")+"ec.tynt.com",wb=(Tynt.e||"")+"sc.tynt.com/script/sc/",xb=["","Attribution","Attribution Share Alike","Attribution No Derivatives",
"Attribution Non-Commercial","Attribution Non-Commercial Share Alike","Attribution Non-Commercial No Derivatives"],yb=["","http://creativecommons.org/licenses/by/3.0","http://creativecommons.org/licenses/by-sa/3.0","http://creativecommons.org/licenses/by-nd/3.0","http://creativecommons.org/licenses/by-nc/3.0","http://creativecommons.org/licenses/by-nc-sa/3.0","http://creativecommons.org/licenses/by-nc-nd/3.0"],ha=null,zb=function(){if(/tynt-mobile-ss-test/.test(location.href))return true;if(i.ss)if(ba()&&
ba()&&N("m"))return true;else if(!ba())return true;return false},Ab=function(a){return(a=a.match(/axzz([^?$]*)/))&&a.length==2?a[1]:null},Bb=function(a){r(C+"/b/a?g="+a+"&id="+B+"&r="+encodeURIComponent(E(h.referrer))+"&ts="+u(),function(){})},Ta=function(a){return a.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;")},Cb=function(){var a;ha=false;if(typeof window.getSelection==="function")if(typeof document.createRange==="function"){var b=window.getSelection();if(!(typeof b.addRange!==
"function"||typeof b.removeAllRanges!=="function"||typeof b.rangeCount!=="number")){var c=[];for(a=0;a<b.rangeCount;a++)c.push(b.getRangeAt(a));a=document.body.appendChild(document.createElement("div"));a.contentEditable="false";var d=a.appendChild(document.createTextNode("\u00a0\u00a0\u00a0")),e=document.createRange(),f=e.cloneRange();e.setStart(d,0);f.setEnd(d,3);f.setStart(d,2);b.removeAllRanges();b.addRange(e);b.addRange(f);ha=b.rangeCount==2;document.body.removeChild(a);b.removeAllRanges();e.detach();
f.detach();for(a=0;a<c.length;a++)b.addRange(c[a])}}},U=false,Db=function(a){var b,c="";ha===null&&Cb();if(U)return false;U=true;var d="";if(i.a){var e=M(a);if(typeof trackAttributionView!=="undefined")c='<img src="https://'+C+"/b/l?id="+P()+"&g="+a+'">';a=c+'<a style="color: #003399;" href="';d+=i.ap+" ";if(i.st)d=d+a+e+'">'+Ta(S)+"</a> ";if(i.su)d=d+a+e+'">'+Ta(e)+"</a>";if(i.as.length>0)d=d+"\n<br>"+i.as+" ";if(i.cc>0)d=d+"\n<br>Under Creative Commons License: "+a+yb[i.cc]+'">'+xb[i.cc]+"</a>";
if(i.w||i.f){d+="\n<br>Follow us: ";if(i.w)d=d+'<a href="http://'+Sa+"/b/rw?id="+P()+"&u="+i.w+'" target="_blank">@'+i.w+" on Twitter</a>";if(i.w&&i.f)d+=" | ";if(i.f)d=d+'<a href="http://'+Sa+"/b/rf?id="+P()+"&u="+i.f+'" target="_blank">'+i.f+" on Facebook</a>"}}if(i.el){if(d.length>0)d+="\n<br>";d+=i.el}var f,g;f=q("div",{},{overflow:"hidden",color:"#000000",backgroundColor:"#FFFFFF",textAlign:"left",textDecoration:"none",border:"none"});if(h.selection&&h.selection.createRange){var j=s.scrollLeft||
l.scrollLeft,k=s.scrollTop||l.scrollTop;g=q("div",{},{overflow:"hidden",position:"absolute",left:j+20+"px",top:k+20+"px",width:"1px",height:"1px"});l.insertBefore(g,l.firstChild);var p=h.selection.createRange();f.innerHTML=i.t?d+"<br><br>"+p.htmlText:p.htmlText+"<br><br>"+d;Ja(f);g.appendChild(h.createElement("br"));g.appendChild(f);d=l.createTextRange();d.moveToElementText(f);d.select();setTimeout(function(){l.removeChild(g);if(p.text!==""){p.select();s.scrollLeft=j;l.scrollLeft=j;s.scrollTop=k;
l.scrollTop=k}U=false},0)}else if(ha){b=getSelection();g=q("div",{},{height:0,position:"absolute",top:"-1000px"});g.innerHTML="<br>";if(i.t){l.insertBefore(g,l.firstChild);f.innerHTML=d+"<br><br>"}else{l.appendChild(g);f.innerHTML="<br>"+d+"<br>"}g.appendChild(f);d=h.createRange();d.selectNode(f);b.addRange(d);window.setTimeout(function(){g.parentNode.removeChild(g);U=false},0)}else{b=getSelection();var o=b.getRangeAt(0);d=q("span",{innerHTML:d});if(i.t){d.innerHTML+="<br/><br/>";f.appendChild(d);
f.appendChild(o.cloneContents())}else{f.appendChild(o.cloneContents());d.innerHTML="<br/><br/>"+d.innerHTML;f.appendChild(d)}Ja(f);f.style.width=0.1;f.style.height=0.1;f.style.position="absolute";f.style.top="-1000px";f.style.left="-1001px";f.appendChild(h.createElement("br"));d=f.innerText.length;l.insertBefore(f,l.firstChild);if(f.innerText.length!=d)f.style.overflow="";b.selectAllChildren(f);setTimeout(function(){f.parentNode.removeChild(f);b.removeAllRanges();b.addRange(o);U=false},0)}return true},
Fb=function(a,b){var c=true;if(i.a||i.el){var d;d=z(b);d=d.length>=2?$(d.charAt(0))||$(d.charAt(d.length-1))||$(d.charAt(d.length/2)):$(d);var e;if(e=i.h)a:{e=(e=Eb())?e.className.split(/\s+/):[];for(var f=e.length-1;f>=0;f--)if(i.h[e[f]]!==undefined){e=i.h[e[f]];break a}e=void 0}e=e;if(e!==false&&(d&&b.replace(/\s/g,"").length>=i.aw*2||!d&&Y(b)>=i.aw)||e)if(i.a||i.el){c=Db(a.g);if(i.a)a.trace_type=0}}return c},Eb=function(){return!h.selection||!h.selection.createRange?function(){var a=getSelection().getRangeAt(0),
b=a.startContainer.nodeType==3?a.startContainer.parentNode:a.startContainer;return b&&z(a.toString())==z(b.textContent)?b:null}:function(){var a=h.selection.createRange(),b=a.duplicate();b.collapse(true);return(b=b.parentElement())&&z(a.text)==z(b.innerText)?b:null}}(),Gb=function(a){var b=a?864E5:-5E3;b=new Date(u()+b);h.cookie="tracerabg="+a+";path=/;expires="+b.toUTCString()},Ib=function(a){var b;a:{b=h.getElementsByTagName("script");for(var c=0;c<b.length;c++)if(/\/show_afs_search\.js/i.test(b[c].src)){b=
true;break a}b=false}if(!b&&Hb(location)){Tynt.b=a||L(location.href);location.replace(location.href+(location.href[location.href.length-1]==="#"?"":"#")+"axzz"+Tynt.b)}},Hb=function(a){if(!(a.hash===""||a.hash==="#"))return false;if(typeof i.ba=="boolean"&&i.ba)i.ba=["/"];else if(!i.ba)return true;for(var b,c=i.ba.length-1;c>=0;c--){b=null;var d=i.ba[c],e=d.indexOf("/");if(e!==0){b=d.slice(0,e);d=d.slice(e)}if(!b||a.host==b)if(d.charAt(d.length-1)=="#"){if(a.pathname.indexOf(d.slice(0,-1))===0)return false}else if(a.pathname==
d)return false}return true},ia;Tynt.getConfig=function(){if(typeof ia!=="undefined"&&ia!==null)return ia;return ia=typeof JSON!=="undefined"&&typeof JSON.parse==="function"&&typeof JSON.stringify==="function"?JSON.parse(fb(i)):i};var ja=0,Ua;fa=function(){Tynt.sc=function(c){clearTimeout(b);ja=c.fl||0;var d=ka;c=(c=c)||{};if(c.d===true){c=c;G(Tynt.o||{},c);d=c;if(ra(Tynt.overrides))for(var e=0;Tynt.overrides.length>=e;e++)typeof Tynt.overrides[e]==="object"&&G(Tynt.overrides[e],d)}else{c=Tynt.i||
window.tyntVariables||{};G(c,d);c=d;if(!c.ap&&typeof tyntAP!="undefined")c.ap=tyntAP;if(!c.as&&typeof tyntAS!="undefined")c.as=tyntAS}i={a:true,ad:true,aw:8,cc:0,b:false,ap:"Read more:",as:"",st:false,su:true,w:false,f:false,ss:"",sic:{}};G(c,i);if(i.a==="0"||i.a===0)i.a=false;if(i.cc>6)i.cc=0;if(i.aw<8)i.aw=8;if(i.su==="0"||i.su===0)i.su=false;if(!/^\w{1,15}$/.test(i.w||""))i.w=false;if(!/^[\w.]{2,}$/.test(i.f||""))i.f=false;if(ja>0){i.a=false;i.b=false}!h.cookie.match(/ty_attributionBlockedByIp=[tf]/)&&
ra(i.ipb)?vb():F("afterIpBlockCheck",i)};var a=wb+ga+".js",b=setTimeout(function(){Tynt.sc({fl:1})},1E4);Ua=u();la(a)};A.afterIpBlockCheck.push(function(){ja===0&&!wa()&&Tynt.m.push(Fb);if(i.b&&!wa()){var a=Ab(location.href);if(a){if("#axzz"+ma(h.cookie,"tracerabg")!=location.hash)if(!(h.referrer?K(h.referrer).host===K(h.location.hostname).host:false)){Bb(a);Ka(2)}}else{Ib(ma(h.cookie,"tracerabg"));Gb(Tynt.b)}}if(zb()&&!wa()){if(aa(l).position=="relative")l.style.position="static";Tynt.m.push(nb);
X(tb)}if(Tynt.e||Math.random()<0.0010){a=["?is=",ja,"&id=",B,"&rt=",u()-Ua,"&ts=",u()];a=W+a.join("");r(a)}F("afterDynamicConfig",i);X(function(){F("afterDynamicConfigAndDocumentLoaded",i)})});var Va=function(){var a=h.title.indexOf("#ixzz");if(a>-1)h.title=h.title.substring(0,a);a=h.title.indexOf("#axzz");if(a>-1)h.title=h.title.substring(0,a)},Jb=function(){for(var a=0;a<Tynt.length;a++)if(Tynt[a]&&Tynt[a].length==22)return Tynt[a];return null},ka=function(a){if(!a)return{};for(var b={},c=a.substring(a.indexOf("?")+
1).split("&"),d=0;d<c.length;d++){var e=c[d].split("=");if(e[0].indexOf("amp;")===0)e[0]=e[0].substring(4);b[e[0]]=e[1]}a=a.split("/");a.pop();b.scriptPathUri=a.join("/");return b}(function(){for(var a=h.getElementsByTagName("script"),b=0;b<a.length;b++)if(/\/tracer.*\?/i.test(a[b].src))return a[b].src;return null}()),ga=ka.user||Jb();if(!ga)throw Error("Error finding Tynt Insight userId. Please check your HTML for errors.");ka.user&&Tynt.push(ka.user);/tracer=test/.test(location.href)&&r(Aa+"/script/verify/"+
ga);(function(){if(/disableTracer=/.test(location.href)){var a=location.href.match(/disableTracer=([^?$]*)/)[1],b=new Date;b.setDate(a&&a=="on"?b.getDate()+365:b.getDate()-2);R("disableTracer="+(a&&a=="on"?"y":"n"),"expires="+b.toUTCString());b=q("div",{id:"TyntLocalOptOut"},{zIndex:"10000",position:"absolute",top:"10%",left:"10%",width:"80%",height:"80%",backgroundColor:"white",color:"black",textAlign:"center",fontSize:"32px",paddingTop:"10%",border:"1px solid gray"});b.innerHTML="Tynt Insight has been turned "+
(a&&a=="on"?"off":"on")+" in this browser.<br>You may close this window.";l.insertBefore(b,l.firstChild)}})();if(!Ia()){if(V){Va();h.attachEvent("onpropertychange",Va)}var oa=qa();ib();fa()}if(typeof Wa==="undefined")var Wa=10;(new Date).getDate()===Wa&&function(){var a=document.createElement("script"),b=document.getElementsByTagName("script")[0];a.async="async";a.type="text/javascript";a.src="http://"+Za+"/cb.js";b.parentNode.insertBefore(a,b)}();var xa=null,Xa=0,ya=function(){if(typeof document.body.oncopy==
"object"&&document.body.oncopy!==null){document.body.oncopy=null;y(13)}else setTimeout(ya,2E3)},Kb=function(){if(typeof stlib!=="undefined"&&typeof stlib.hash!=="undefined"&&typeof stlib.hash.doNotCopy!=="undefined"&&!stlib.hash.doNotCopy){ya();setTimeout(function(){clearInterval(xa)},2E3)}Xa+=1;Xa>=5&&clearInterval(xa)};A.afterDynamicConfig.push(function(){if(typeof stlib!=="undefined"&&typeof stlib.hash!=="undefined"&&typeof stlib.hash.doNotCopy!=="undefined"&&!stlib.hash.doNotCopy)ya();else{for(var a=
false,b=document.getElementsByTagName("script"),c=0;c<b.length;c++)if(b[c].getAttribute("src")&&/sharethis/.test(b[c].src)){a=true;break}if(a)xa=setInterval(Kb,2E3)}typeof F==="function"&&F("afterProtectTynt")})};Tynt.TIL=function(){document.body?Lb():setTimeout(Tynt.TIL,300)}})();Tynt.TIL()};
